1526281327318	Sync.LogManager	DEBUG	Flushing file log
1526281327330	Sync.LogManager	DEBUG	Log cleanup threshold time: 1525417327330
1526281327502	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1526281327506	Sync.Service	DEBUG	User-Agent: Firefox/59.0.2 (Linux x86_64) FxSync/1.61.0.20180406121424.desktop
1526281327506	Sync.Service	INFO	Starting sync at 2018-05-14 14:02:07 in browser session qzKXTZzD26AL
1526281327506	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1526281327510	Sync.Status	INFO	Resetting Status.
1526281327510	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1526281327510	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
1526281327536	Sync.LogManager	DEBUG	Done deleting files.
1526281328192	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1526281328192	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1526281328196	Sync.Service	DEBUG	User-Agent: Firefox/59.0.2 (Linux x86_64) FxSync/1.61.0.20180406121424.desktop
1526281328196	Sync.Service	INFO	Starting sync at 2018-05-14 14:02:08 in browser session qzKXTZzD26AL
1526281328198	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync". (resource://services-sync/util.js:43:5) JS Stack trace: LockException@util.js:43:5 < throwLockException@util.js:119:11 < WrappedLock@util.js:133:9 < _lockedSync@service.js:1099:12 < sync/<@service.js:1091:13 < WrappedCatch@util.js:107:22 < sync@service.js:1080:12
1526281328200	Sync.Service	INFO	Cannot start sync: already syncing?
1526281329426	Sync.Resource	WARN	GET request to https://sync-600-us-west-2.sync.services.mozilla.com/1.5/92728811/info/collections failed: [Exception... "The connection was established, but no data was ever received"  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "<unknown>"  data: no] No traceback available
1526281329426	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1526281329426	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1526281329426	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection was established, but no data was ever received"  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "<unknown>"  data: no] No traceback available
1526281329428	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1526281329432	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection was established, but no data was ever received"  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "<unknown>"  data: no] No traceback available
1526281329432	Sync.ErrorHandler	DEBUG	Addons installed: 8
1526281329432	Sync.ErrorHandler	DEBUG	 - Firefox Multi-Account Containers, version 6.0.0, id @testpilot-containers
1526281329432	Sync.ErrorHandler	DEBUG	 - GNOME Shell integration, version 10.1, id chrome-gnome-shell@gnome.org
1526281329432	Sync.ErrorHandler	DEBUG	 - Web Extension for Shaarli, version 2.0.0, id shaarli@imirhil.fr
1526281329432	Sync.ErrorHandler	DEBUG	 - DuckDuckGo Privacy Essentials, version 2018.5.1, id jid1-ZAdIEUB7XOzOJw@jetpack
1526281329432	Sync.ErrorHandler	DEBUG	 - uBlock Origin, version 1.16.4, id uBlock0@raymondhill.net
1526281329432	Sync.ErrorHandler	DEBUG	 - FoxyProxy Standard, version 6.2, id foxyproxy@eric.h.jung
1526281329432	Sync.ErrorHandler	DEBUG	 - Zotero Connector, version 5.0.39, id zotero@chnm.gmu.edu
1526281329432	Sync.ErrorHandler	DEBUG	 - Sync Tab Groups, version 0.6.9, id sync-tab-groups@eric.masseran
