1526540758768	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1526541239428	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1526541239429	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1526541239430	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1526541240390	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1526541678652	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1526541678652	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1526541678656	Sync.Service	DEBUG	User-Agent: Firefox/60.0 (Linux x86_64) FxSync/1.62.0.20180509234620.desktop
1526541678656	Sync.Service	INFO	Starting sync at 2018-05-17 14:21:18 in browser session 8IYZaSGUJ7Gm
1526541678656	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1526541678660	Sync.Status	INFO	Resetting Status.
1526541678660	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1526541678667	Sync.Resource	WARN	GET request to https://sync-600-us-west-2.sync.services.mozilla.com/1.5/92728811/info/collections failed: [Exception... "The connection to the proxy server was refused"  nsresult: "0x804b0048 (NS_ERROR_PROXY_CONNECTION_REFUSED)"  location: "<unknown>"  data: no] No traceback available
1526541678667	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1526541678667	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1526541678667	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection to the proxy server was refused"  nsresult: "0x804b0048 (NS_ERROR_PROXY_CONNECTION_REFUSED)"  location: "<unknown>"  data: no] No traceback available
1526541678668	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1526541678679	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection to the proxy server was refused"  nsresult: "0x804b0048 (NS_ERROR_PROXY_CONNECTION_REFUSED)"  location: "<unknown>"  data: no] No traceback available
1526541678680	Sync.ErrorHandler	DEBUG	Addons installed: 8
1526541678680	Sync.ErrorHandler	DEBUG	 - Firefox Multi-Account Containers, version 6.0.0, id @testpilot-containers
1526541678680	Sync.ErrorHandler	DEBUG	 - GNOME Shell integration, version 10.1, id chrome-gnome-shell@gnome.org
1526541678680	Sync.ErrorHandler	DEBUG	 - Web Extension for Shaarli, version 2.0.0, id shaarli@imirhil.fr
1526541678680	Sync.ErrorHandler	DEBUG	 - DuckDuckGo Privacy Essentials, version 2018.5.1, id jid1-ZAdIEUB7XOzOJw@jetpack
1526541678680	Sync.ErrorHandler	DEBUG	 - FoxyProxy Standard, version 6.2, id foxyproxy@eric.h.jung
1526541678680	Sync.ErrorHandler	DEBUG	 - Zotero Connector, version 5.0.39, id zotero@chnm.gmu.edu
1526541678681	Sync.ErrorHandler	DEBUG	 - Sync Tab Groups, version 0.6.9, id sync-tab-groups@eric.masseran
1526541678681	Sync.ErrorHandler	DEBUG	 - uBlock Origin, version 1.16.6, id uBlock0@raymondhill.net
